/*
 * USART_CONFIG.h
 *
 *  Created on: Sep 19, 2023
 *      Author: Misra
 */

#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define USART1_SAMPLING_SELECTED				USART1_OVER16

#define USART1_STATUS							USART1_ENABLED

#define USART1_WORD_LENGTH						DATA_8BIT

#define USART1_PARITY_STATUS					PARITY_DISABLED

#define USART1_PARITY_SELECTION					EVEN_PARITY

#define USART1_TRANSMIT_STATUS					TRANSMIT_ENABLED

#define USART1_RECEIVER_STATUS					RECEIVER_ENABLED

#define USART1_STOP_BITS_SELECTION				STOPBITS_1

#define USART_CLK_PIN_STATUS					CLK_PIN_ENABLED

#define USART1_CPOL_STATUS						CPOL_LOW

#define USART1_CPHA_STATUS						CPHA_READ_FIRST

#define USART1_HALF_DUPLEX_SELECTED				HALF_DUPLEX_DISABLED

#define USART1_PRESCALAR_SLECTED				PRESCALAR_2



#endif /* USART_CONFIG_H_ */
